web/controllers/Index.py
from flask import Blueprint
from flask import render_template
index_route = Blueprint('index_page', __name__)


@index_route.route('/')
def index():
    return render_template('index.html')

web/templates/index.html
{% extends "layout.html" %}

{% block content %}
    后台首页的主体内容
{% endblock %}

web/templates/layout.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>
            {% block title %} {{config.PROJECT_TITLE}} {% endblock %}
        </title>
        <link rel="stylesheet" href="{{ url_for('static', filename='bootstrap/css/bootstrap.css') }}">
        <link rel="stylesheet" href="{{ url_for('static', filename='css/admin/style.css') }}">
        {% block othercss %}{% endblock %}
    </head>
    <body>
        <div class="container">
            <nav class="navbar navbar-default">
              <div class="container-fluid">
                <!-- Brand and toggle get grouped for better mobile display -->
                <div class="navbar-header">
                  <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                          data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                  </button>
                  <a class="navbar-brand" href="#">{{config.PROJECT_TITLE}}</a>
                </div>

                <!-- Collect the nav links, forms, and other content for toggling -->
                <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                  <ul class="nav navbar-nav navbar-right">
                    <li class="dropdown">
                      <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button"
                         aria-haspopup="true" aria-expanded="false">{{ session.username }}
                          <span class="caret"></span>
                      </a>
                      <ul class="dropdown-menu">
                        <li>
                            <a href="{{url_for('user_page.logout')}}">退出</a>
                        </li>
                        <li role="separator" class="divider"></li>
                        <li><a href="#">修改密码</a></li>
                      </ul>
                    </li>
                  </ul>
                </div><!-- /.navbar-collapse -->
              </div><!-- /.container-fluid -->
            </nav>
            <div class="row">
                <div class="col-md-2">
                    <div class="list-group">
                      <a href="{{url_for('index_page.index')}}" class="list-group-item
                      {% if isActive(request.path) == '/' %} active {% else %} {% endif %}">常用管理</a>
                      <a href="{{url_for('user_page.index')}}" class="list-group-item
                      {% if isActive(request.path) == 'user' %} active {% else %} {% endif %}">管理员管理</a>
                    </div>
                </div>
                <div class="col-md-10">

                    <!--flash消息提示开始-->
                    {% with messages = get_flashed_messages(with_categories=true) %}
                    {% for category, message in messages %}
                    <div class="alert {% if category=='error' %} alert-danger {% else %} alert-success {% endif %} alert-dismissible" role="alert">
                      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                          <span aria-hidden="true">&times;</span>
                      </button>
                      <strong>提示：</strong> {{ message }}
                    </div>
                    {% endfor %}
                    {% endwith %}
                    <!--flash消息提示结束-->

                    {% block content %}
                    <!--  主体内容  -->
                    {% endblock %}
                </div>
            </div>
            <div class="row">
                <p class="text-center">©2020 Powered by <a href="http://www.moocba.com">{{config.SUPPORT}}</a></p>
            </div>
        </div>
        <script src="{{ url_for('static', filename='js/jquery.1.10.2.min.js') }}"></script>
        <script src="{{ url_for('static', filename='bootstrap/js/bootstrap.js') }}"></script>
        {% block otherjs %}

        {% endblock %}
    </body>
</html>

web/templates/login.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>登录-后台管理系统</title>
        <link rel="stylesheet" href="{{ url_for('static', filename='bootstrap/css/bootstrap.css') }}">
        <link rel="stylesheet" href="{{ url_for('static', filename='css/admin/login.css') }}">
    </head>
    <body>
        <div class="container">
            <div class="row">
                <div class="col-sm-4 col-sm-offset-4">
                    <!--flash消息提示开始-->
                    {% for message in get_flashed_messages() %}
                    <div class="alert alert-warning alert-dismissible" role="alert">
                      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                          <span aria-hidden="true">&times;</span>
                      </button>
                      <strong>提示：</strong> {{ message }}
                    </div>
                    {% endfor %}
                    <!--flash消息提示结束-->

                    <form class="form-horizontal" action="{{ url_for('.login') }}" method="POST">

                          <div class="form-group">
                              <div class="row">
                                    <h2 class="text-center">{{config.PROJECT_TITLE}}</h2>
                              </div>
                          </div>
                          <div class="form-group">
                                <div class="col-sm-12">
                                    <input type="text" name="username" class="form-control input-lg"
                                           required autofocus placeholder="Username">
                                </div>
                          </div>
                          <div class="form-group">
                                <div class="col-sm-12">
                                    <input type="password" name="password" placeholder="Password"
                                           class="form-control input-lg" required>
                                </div>
                          </div>
                          <div class="form-group">
                                <div class="col-sm-12">
                                    <button type="submit" class="btn btn-primary btn-lg btn-block">登录</button>
                                </div>
                          </div>
                    </form>
                </div>
            </div>

        </div>
        <script src="{{ url_for('static', filename='js/jquery.1.10.2.min.js') }}"></script>
        <script src="{{ url_for('static', filename='bootstrap/js/bootstrap.js') }}"></script>
    </body>
</html>

web/templates/user/add.html
{% extends 'layout.html' %}

{% block title %}新增管理员-新闻管理系统{% endblock %}

{% block content %}
    <form class="form-horizontal" role="form" method='POST' novalidate>
      <div class="form-group {% if form.login_name.errors %} has-error {% endif %}">
          <label class="col-sm-2 control-label">{{ form.login_name.label }}</label>
          <div class="col-sm-4">
              {{ form.login_name }}
          </div>
          <div class="col-sm-6">
              {% for error in form.login_name.errors %}
                <p class="text-danger">{{ error }}</p>
              {% endfor %}
          </div>
      </div>
      <div class="form-group {% if form.login_pwd.errors %} has-error {% endif %}">
          <label class="col-sm-2 control-label">{{ form.login_pwd.label }}</label>
          <div class="col-sm-4">
              {{ form.login_pwd }}
          </div>
          <div class="col-sm-6">
              {% for error in form.login_pwd.errors %}
              <p class="text-danger">{{ error }}</p>
              {% endfor %}
          </div>
      </div>
      <div class="form-group {% if form.repassword.errors %} has-error {% endif %}">
          <label class="col-sm-2 control-label">{{ form.repassword.label }}</label>
          <div class="col-sm-4">
              {{ form.repassword }}
          </div>
          <div class="col-sm-6">
              {% for error in form.repassword.errors %}
              <p class="text-danger">{{ error }}</p>
              {% endfor %}
          </div>
      </div>
      <div class="form-group">
        <label class="col-sm-2 control-label"></label>
        <div class="col-sm-6">
            {{ form.status }} {{ form.status.label }}
        </div>
      </div>
      <div class="form-group">
        <label class="col-sm-2 control-label"></label>
        <div class="col-sm-10">
            {{ form.hidden_tag() }}
            {{ form.submit }}
        </div>
      </div>
    </form>

{% endblock %}

web/templates/user/edit.html
{% extends 'layout.html' %}

{% block title %}编辑管理员-新闻管理系统{% endblock %}

{% block content %}
    <form class="form-horizontal" role="form" method='POST' novalidate>
      <div class="form-group {% if form.login_name.errors %} has-error {% endif %}">
          <label class="col-sm-2 control-label">{{ form.login_name.label }}</label>
          <div class="col-sm-4">
              {{ form.login_name }}
          </div>
          <div class="col-sm-6">
              {% for error in form.login_name.errors %}
                <p class="text-danger">{{ error }}</p>
              {% endfor %}
          </div>
      </div>
      <div class="form-group {% if form.login_pwd.errors %} has-error {% endif %}">
          <label class="col-sm-2 control-label">{{ form.login_pwd.label }}</label>
          <div class="col-sm-4">
              {{ form.login_pwd }}
          </div>
          <div class="col-sm-6">
              {% for error in form.login_pwd.errors %}
              <p class="text-danger">{{ error }}</p>
              {% endfor %}
          </div>
      </div>
      <div class="form-group {% if form.repassword.errors %} has-error {% endif %}">
          <label class="col-sm-2 control-label">{{ form.repassword.label }}</label>
          <div class="col-sm-4">
              {{ form.repassword }}
          </div>
          <div class="col-sm-6">
              {% for error in form.repassword.errors %}
              <p class="text-danger">{{ error }}</p>
              {% endfor %}
          </div>
      </div>
      <div class="form-group">
        <label class="col-sm-2 control-label"></label>
        <div class="col-sm-6">
            {{ form.status }} {{ form.status.label }}
        </div>
      </div>
      <div class="form-group">
        <label class="col-sm-2 control-label"></label>
        <div class="col-sm-10">
            {{ form.hidden_tag() }}
            {{ form.submit }}
        </div>
      </div>
    </form>

{% endblock %}

web/templates/user/index.html
{% extends 'layout.html' %}

{% block title %}管理员列表-{{config.PROJECT_TITLE}}{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-md-6">
            <a href="{{url_for('.add')}}" class="btn btn-primary">新增管理员</a>
        </div>
        <div class="col-md-6">
            <form action="#" class="form-inline pull-right">
                <input type="text" name="search" class="form-control" placeholder="请输入账号">
                <input type="submit" value="查询" class="btn btn-primary">
            </form>
        </div>
    </div>
    <div class="row mt20">
        <div class="col-md-12">
            <table class="table table-striped table-bordered">
              <thead>
                <tr>
                  <th>管理员ID</th>
                  <th>管理员账号</th>
                  <th>管理员状态</th>
                  <th>操作</th>
                </tr>
              </thead>
              <tbody>
                {% if users.total  %}
                {% for item in users.items %}
                <tr>
                  <th scope="row">{{ item.id }}</th>
                  <td>{{ item.login_name }}</td>
                  <td>
                      {% if item.status %}
                      <span class="text-primary">开启</span>
                      {% else %}
                      <span class="text-danger">禁用</span>
                      {% endif %}
                  </td>
                    {% if item.login_name == "admin" %}
                    <td></td>
                    {% else %}
                  <td>
                      <a href="{{url_for('.edit', pk=item.id)}}" class="btn btn-primary btn-sm">编辑</a>
                      <button data-toggle="modal" data-target="#myModal" class="btn btn-danger btn-sm" data-url="{{url_for('.delete', pk=item.id)}}">删除</button>
                  </td>
                    {% endif %}
                </tr>
                {% endfor %}
                {% else %}
                <tr>
                    <td colspan="4">暂无结果！</td>
                </tr>
                {% endif %}
              </tbody>
            </table>
        </div>
        {% include "public/pagenation.html" %}
    </div>

    {# 删除提示框 #}
    <div class="modal fade" tabindex="-1" role="dialog" id="myModal">
          <div class="modal-dialog" role="document">
            <div class="modal-content">
              <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">删除提示</h4>
              </div>
              <div class="modal-body">
                <p>你确定删除该条数据吗？</p>
              </div>
              <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">取消</button>
                <a href="#" class="btn btn-primary" id="J_deleteBtn">确定</a>
              </div>
            </div><!-- /.modal-content -->
          </div><!-- /.modal-dialog -->
    </div><!-- /.modal -->
{% endblock %}

{% block otherjs %}

<script>
    {#给所有的删除按钮元素设置点击事件#}
    $('button.btn-danger').on('click', function(){
        {#alert($(this).attr('data-url'))#}
        {#获取当前点击按钮元素的data-url属性的属性值#}
        var url = $(this).attr('data-url')
        {#给删除的确定按钮设置href属性的属性值#}
        $('#J_deleteBtn').attr('href', url)
    })
</script>

{% endblock %}